### ISSUE TITLE
Question on waypoints and jquery-circle-progress

### ISSUE THREAD

**Issue by soniapello** [kottenator/jquery-circle-progress#145]
Hi!

I wonder if it's possible to have the circle progress and animate it on waypoints. Because now the circle doesn't show and it appears when the offset is reach.

I've made a [stackoverflow question here](http://stackoverflow.com/questions/43572162/jquery-waypoints-on-specific-animation) with the demo.

Thanks!

**Comment by kottenator** [comment]
Hi!

I've [answered you on SO](http://stackoverflow.com/questions/43572162/jquery-waypoints-on-specific-animation#answer-43576523).

Shortly:

1. Init the circle with `value: 0` 0 it will render it "empty"
2. do `.circleProgress({value: realValue})` when the circle reaches the _waypoint_

Here's [a working demo](http://jsbin.com/qupohek/3/edit?js,output), and [another demo](http://jsbin.com/wawozic/3/edit?html,js,output) _(a bit different implementation)_, and [one more demo](http://jsbin.com/wawozic/1/edit?html,js,output) _(using jQuery Appear instead of jQuery Waypoints)_.

This issue is related to #8. As you can see, one of the first project issues/questions was about the lazy rendering :)

**Comment by kottenator** [comment]
I hope I've helped you. I'm closing this ticket, but feel free to reopen.

**Comment by soniapello** [comment]
@kottenator  you've helped me a lot thanks
I 've seen the demo you've made[ here](http://jsbin.com/nokenef/3/edit?html,css,js,output) but I wonder how you get multiple circles because I've trying to do it with jquery each like 
```
  $( "#circle" ).each(function() {
    var el = $('#circle').circleProgress({value: 0});
  });


new Waypoint({
  element: el.get(0),
  handler: function() {
    el.circleProgress({
      value: el.data('value')
    });
    this.destroy();
  },
  offset: '50%'
});

``` 
but it doesn't seems to be right

**Comment by kottenator** [comment]
In [this link](http://jsbin.com/wawozic/3/edit?html,js,output) I use `Waypoints` with multiple circles.

If you want to make it in pure JS (though it'd be not 100% pure because of my plugin):

```js
var elements = document.querySelectorAll('.circle');

Array.prototype.slice.apply(elements).forEach(function(el) {
  var $el = $(el);

  $el.circleProgress({value: 0});

  new Waypoint({
    element: el,
    handler: function() {
      $el.circleProgress({
        value: $el.data('value')
      });
      this.destroy();
    },
    offset: '50%'
  });
});
```

[Here's a demo example](http://jsbin.com/bumujaj/2/edit?html,js,output).
