### ISSUE TITLE
Cancel a previous value animation when a new one is recieved

### ISSUE THREAD

**Issue by TheDarkVoid** [kottenator/jquery-circle-progress#151]
I'm having an issue where it seems that the animation isn't progressing because the value is updated before that last update finishes it's animation resulting in the circle not reflecting the correct progress. Is there a workaround for this or a way for me to send continuous value changes to the circle and have it respond according abandoning the previous request?
Below is my code:  
```Javascript
	art.circleProgress({
		value: 0,
		size: 180,
		fill:{color:"#f1eaf9"}
	});
	var loadProgress = $("#player #loadProgress");
	player.on('buffer', function(p)
	{
		loadProgress.text(Math.round(p) + "%");
		art.circleProgress('value', (p/100));
		if(p == 100)
		{
			loadProgress.fadeOut();
			art.children("canvas").fadeOut(function(){
				playIcon.fadeIn();
			});
		}
	});
```
[Image](https://aobacapture.com/i/836wcYZSYUW6t7-0eurS5w)

**Comment by kottenator** [comment]
There're two things you can do:

1. `$($circleEl.data('circle-progress').canvas).stop(true, true); $circleEl.circleProgress('value', nextValue)` - "jump" to the end of the current animation before starting the next one
2. `$circleEl.circleProgress({animation: {duration: 100}});` - make the animation faster, or even disable the animation

The problem is that I'm using `jQuery(...).animate(...)` which doesn't provide much flexibility.

Read more in the #42 ticket.

**Comment by TheDarkVoid** [comment]
I ended up going with the second option of reducing the duration.
