### ISSUE TITLE
Every thought of making the circles for retina displays?

### ISSUE THREAD

**Issue by emilkarl** [kottenator/jquery-circle-progress#26]
![image](https://cloud.githubusercontent.com/assets/10711/6941745/af5dcb68-d882-11e4-86d2-ab9b9d81df35.png)

**Comment by kottenator** [comment]
You could make it twice bigger in JS config but then resize the canvas to 50% size with CSS.

There was a [similar issue](https://github.com/kottenator/jquery-circle-progress/issues/17) about responsive design, please check if it would help.

And I would appreciate if you will advise a better way to do that, because I don't like the one I proposed.

**Comment by kottenator** [comment]
I hope I solved your problem. I'm closing the ticket
