### ISSUE TITLE
Stop function

### ISSUE THREAD

**Issue by bderongs** [kottenator/jquery-circle-progress#37]
Hi,

Thank you for your plugin, it is the nicest and easiest I have found. I may have missed something but is there any way to stop the timer at the value it is ?
When I do
var A = $("#myElement").circleProgress({...})

I have tried
- A.stop() => Does nothing
- A.circleProgress('stop')  => Redraw the circle

Baptiste

**Comment by kottenator** [comment]
Hi!

Currently you may stop animation with next:

```js
var el = $('.circle').circleProgress({/*...*/});
$(el.circleProgress('widget')).stop();
```

I understand that it's not obvious, so it's good idea to include special "stop" method in next version.

I will leave this issue open to not forget to do this.

**Comment by bderongs** [comment]
Thanks, its works perfectly.

**Comment by kottenator** [comment]
I decided not to implement it (because it brings an ambiguity about current value) but to mention the solution in documentation.

**Comment by hellozhangran** [comment]
i can stop the circel but then , how can i restart it  ?

**Comment by bderongs** [comment]
I personaly redraw it with the correct values :

In the progress function I update a stepValueLeft variable
`self.stepValueLeft = self.timeDuration-self.timeDuration*stepValue;`

Then I have declared a restart function like this one below :

```
  this.restart = function(){
    this.timerObject.circleProgress({
        value:1,
        animationStartValue: this.stepValue,
        animation:{
          duration: this.stepValueLeft,
          easing: "linear"
        }
    });
  };
```

Probably not the most optimal solution but it works fine.

**Comment by najaeng** [comment]
hello! i want to change the progress circle into just the circle image when upload a lot of file. how can i do this? and sorry for my grammar^^;

**Comment by hioctane321** [comment]
This worked great to stop it but for some reason it's triggering the circle-animation-end event. I had to change the event to a circle-animation-progress and time the event in order to prevent my actions from triggering too early.

UPDATE:
I decided to try again from scratch and the circle-animation-end behaved properly this time. No idea why the first attempt failed. I suspect I had some bad math in triggering my stop.  

Also, for those who needed help executing a restart I managed to stop and restart from where the bar left off by grabbing circle-animation-progress value: 
```
.on('circle-animation-progress', function(e,p,v) {
	newStartValue = v.toPrecision(2);
});
```
