### ISSUE TITLE
Progress chart segments

### ISSUE THREAD

**Issue by jacobnbrum** [kottenator/jquery-circle-progress#43]
Hi, I really like your library. I was wondering if there was a way to split up the chart into segments, similarly to the way it is done in this picture. 
![screenshot_2015-07-30-15-14-20](https://cloud.githubusercontent.com/assets/9966112/9043534/1fc96d0e-39e4-11e5-87a6-9f5ecafb6c74.jpg)

Thanks

**Comment by kottenator** [comment]
Hi! [Check out my demo](http://jsbin.com/haxevo/2), I hope it helps

**Comment by jacobnbrum** [comment]
Thanks, that's very nice.
I wonder why it doesn't work in chrome.

**Comment by kottenator** [comment]
That's interesting. It appears that none of my demos works in Chrome. The problem is that I'm including my lib JS directly from GitHub, that doesn't want to be a CDN so they add specific HTTP header which disallows such usage. However, Firefox ignores this header and it works. But Chrome respects this header and my JS is not loaded. 

I've updated the demo, please, check it

**Comment by jacobnbrum** [comment]
Yeah looks awesome in chrome (in general as well), thanks.

**Comment by michalkkkd** [comment]
@kottenator this is awesome. Can you add it to the main library? I almost missed this option :)
