### ISSUE TITLE
Any plans for requestAnimationFrame ?

### ISSUE THREAD

**Issue by danyj** [kottenator/jquery-circle-progress#69]
Nice plugin  but it does spike the timeline a bit when using multiple or large canvas. Do you mind adding requestAnimationFrame ?

https://github.com/rendro/easy-pie-chart/blob/97b5824bf423410c3c6a1e971860159f17ee6ee6/dist/easypiechart.js#L115-L125

**Comment by kottenator** [comment]
That's very nice suggestion! I'll add it

**Comment by danyj** [comment]
:+1:

**Comment by kottenator** [comment]
Back to `requestAnimationFrame` question.

Currently `jquery-circle-progress` is a `jQuery` plug-in and it uses `jQuery.animate(...)` for the circle animation. `jQuery.animate(...)` [will use](https://github.com/jquery/jquery/blob/3.0.0-beta1/src/effects.js#L660) `requestAnimationFrame` in `jQuery#3.x`.

So I guess this issue is out of scope right now and I'm going to close it.

_However_ I'm planning to refactor the library and remove `jQuery` dependency in future. In that case I will use some animation library that uses `requestAnimationFrame` _or I'll create it by myself_.
