### ISSUE TITLE
Can't trigger animation start

### ISSUE THREAD

**Issue by ibumba** [kottenator/jquery-circle-progress#77]
Can't trigger event that is on line 323:
`el.trigger('circle-animation-start');`

jsFiddle example (not working):
https://jsfiddle.net/zzujo/2pn0wb1h/4/

I replaced that line of code with this one and it works:
`setTimeout(function () {
el.trigger('circle-animation-start');
}, 1);`

**Comment by kottenator** [comment]
You may call it a bug but I'd call it a feature :)

The problem is that animation is auto-started on init. Let's look at the example:

```js
el
  .circleProgress({ value: 0.5 })
  .on('circle-animation-start', function(event) {
    alert('Animation started');
  });
```
This alert will not appear because you attach event listener after the event has been triggered already.

However, the following will work:
```js
el
  .on('circle-animation-start', function(event) {
    alert('Animation started');
  })
  .circleProgress({ value: 0.5 });
```

Here is working demo: https://jsfiddle.net/2pn0wb1h/11/

_Note:_ when you _restart_ the animation - the event will be triggered in both examples.

**Comment by kottenator** [comment]
I hope I've solved your problem.
